### ISSUE TITLE
Setting absolute paths in or_sky130-env.yml when testing hammer setup

### ISSUE THREAD

**Issue by LicMiF** [elektrotehnika/digel-asic-labs-fa24#1]
Command specified in hammer setup testing instructions:
```shell
sed  "s;~;$HOME;g" configs-env/or_sky130-env.yml
```
only displays substituted paths to stdout.

I later had issues trying to run build and syn with ~ remaining in or_sky130-env.yml.

Adding -i option changes the file in place.

```shell
sed  -i "s;~;$HOME;g" configs-env/or_sky130-env.yml
```

**Comment by zola1919** [comment]
Can confirm, adding ``` -i``` fixes said issue.
